"""empty message

Revision ID: 10f9be5a3ef6
Revises: 3d29382bcd16
Create Date: 2024-09-30 18:57:13.426590

"""

import sqlalchemy as sa
from alembic import op
from djgram.db.pydantic_field import PydanticField
import tools.audio_processing.pipeline

# revision identifiers, used by Alembic.
revision = "10f9be5a3ef6"
down_revision = "3d29382bcd16"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audioprocessingprofile",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("audio_pipeline", PydanticField(tools.audio_processing.pipeline.AudioPipeline), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audioprocessingprofile")
    # ### end Alembic commands ###
