"""empty message

Revision ID: 471ead140387
Revises: 10f9be5a3ef6
Create Date: 2024-10-01 18:15:50.065002

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy_file import FileField

# revision identifiers, used by Alembic.
revision = "471ead140387"
down_revision = "10f9be5a3ef6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("yt_dlp_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "video",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("playlist_id", sa.String(), nullable=True),
        sa.Column("file", FileField(), nullable=True),
        sa.Column("waiters_ids", sa.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("yt_dlp_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processedvideo",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("original_video_id", sa.String(), nullable=False),
        sa.Column("waiters_ids", sa.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["original_video_id"],
            ["video.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processedvideo")
    op.drop_table("video")
    op.drop_table("playlist")
    # ### end Alembic commands ###
