"""empty message

Revision ID: e6dbf0417a87
Revises: 471ead140387
Create Date: 2024-10-02 00:02:25.398710

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e6dbf0417a87"
down_revision = "471ead140387"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist_video",
        sa.Column("playlist_id", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
        ),
        sa.PrimaryKeyConstraint("playlist_id", "video_id"),
    )
    op.drop_constraint("video_playlist_id_fkey", "video", type_="foreignkey")
    op.drop_column("video", "playlist_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("video", sa.Column("playlist_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key("video_playlist_id_fkey", "video", "playlist", ["playlist_id"], ["id"])
    op.drop_table("playlist_video")
    # ### end Alembic commands ###
