"""empty message

Revision ID: a812d49a6dad
Revises: b238431ce14f
Create Date: 2024-10-11 01:51:46.729458

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy_file import FileField

# revision identifiers, used by Alembic.
revision = "a812d49a6dad"
down_revision = "b238431ce14f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("processedvideo", sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("video", sa.Column("thumbnail", FileField(), nullable=True))
    op.add_column("video", sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "meta")
    op.drop_column("video", "thumbnail")
    op.drop_column("processedvideo", "meta")
    # ### end Alembic commands ###
