"""empty message

Revision ID: 4637f2bb466a
Revises: d7dc6fc988ae
Create Date: 2025-02-22 23:04:36.172639

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4637f2bb466a"
down_revision = "d7dc6fc988ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telegramchatfullinfo", sa.Column("can_send_gift", sa.Boolean(), nullable=True))
    op.alter_column(
        "telegramchatfullinfo",
        "active_usernames",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.alter_column(
        "telegramchatfullinfo",
        "linked_chat_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telegramchatfullinfo",
        "linked_chat_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "telegramchatfullinfo",
        "active_usernames",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    op.drop_column("telegramchatfullinfo", "can_send_gift")
    # ### end Alembic commands ###
